name: Release to PlatformIO

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO build on selected platforms
      run: platformio run -e esp32dev -e nodemcuv2
    
    # - name: Code static analysis
    #   run: platformio check

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .pio/build/*/firmware_*.bin
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true